In [2]:
import tensorflow as tf

tf=tf.compat.v1
tf.disable_eager_execution()


In [35]:
a=tf.fill(tf.ones_like([2,3]).shape,10)
b=tf.constant([[2],[3]])
c=tf.multiply(a,b)
with tf.Session() as s:
    r=s.run(c)
    tf.summary.FileWriter('./graphs1',c.graph)
    print(r)

[[20 20]
 [30 30]]


In [36]:
t1=tf.linspace(10.0,20.0,21)
print(t1)
with tf.Session() as s:
    r=s.run(t1)
    print(r)

Tensor("LinSpace:0", shape=(21,), dtype=float32)
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20. ]


In [37]:
t1=tf.range(10,21,1)
print(t1)
with tf.Session() as s:
    r=s.run(t1)
    print(r)

Tensor("range:0", shape=(11,), dtype=int32)
[10 11 12 13 14 15 16 17 18 19 20]


In [38]:
# Three methods to init variables.

v1=tf.Variable([2])
v2=tf.Variable([3])

# init=tf.global_variables_initializer()
init=tf.variables_initializer([v1,v2],name="ini")
v=tf.mod(v1,v2)
with tf.Session() as s:
    re,p=s.run([init,v])
    # re,re2,p=s.run([v1.initializer,v2.initializer,v])
    print(re)
    print(p)
    tf.summary.FileWriter('./graphs1',s.graph)

None
[2]


In [4]:
a=tf.Variable(20)
aa=a.assign(30)
with tf.Session() as s:
    print(a)
    s.run(a.initializer)
    ab=a.eval()
    print(a)
    print(ab)
    ac=s.run(aa)
    print(a)
    print(ac)
    aaa=a.assign_add(8)
    ad=s.run(aaa)
    print(a.eval())
    print(ad)
    tf.summary.FileWriter('./graph1',aaa.graph)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
<tf.Variable 'Variable:0' shape=() dtype=int32>
<tf.Variable 'Variable:0' shape=() dtype=int32>
20
<tf.Variable 'Variable:0' shape=() dtype=int32>
30
38
38


In [3]:
# Without init function (must explicitly specify close())
a=tf.constant([[20],[30]])
c=tf.add(a,a)
s=tf.InteractiveSession()
# print(a.eval())
print(c.eval())
s.close()

[[40]
 [60]]


In [20]:
a=tf.placeholder(tf.complex64,[2])
b=tf.constant([-2.0 + 4j,-2.0 + 4j],tf.complex64)
c=tf.multiply(a,b)
with tf.Session() as s:
    r=s.run(c,{a: [-2,-2]})
    print(r)

[4.-8.j 4.-8.j]
